name: CI
permissions:
  contents: read

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install NPM package dependencies
        run: npm install
      - name: Check lint
        run: npm run lint
      - name: Typecheck
        run: npm run typecheck
      - name: Run tests
        env:
          AMOY_RPC: '["https://rpc-amoy.polygon.technology"]'
          ETHEREUM_RPC: '["https://rpc.polygon.tools/internal/evm/1?token=${{ secrets.ERPC_CLIENT_TOKEN }}"]'
          MATIC_RPC: '["https://rpc.polygon.tools/internal/evm/137?token=${{ secrets.ERPC_CLIENT_TOKEN }}"]'
          SEPOLIA_RPC: '["https://rpc.polygon.tools/internal/evm/11155111?token=${{ secrets.ERPC_CLIENT_TOKEN }}"]'
          ZKEVM_MAINNET_URL: https://bridge-api.zkevm-rpc.com
          ZKEVM_TESTNET_URL: https://bridge-api.cardona.zkevm-rpc.com
        run: npm run test
